In [6]:
import numpy as np

In [13]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
a

array([[1, 2],
       [3, 4]])

In [14]:
b

array([[5, 6]])

In [15]:
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
np.concatenate((a,b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [17]:
b.T

array([[5],
       [6]])

In [22]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.random.shuffle(a)

In [24]:
a

array([0, 4, 3, 2, 1, 8, 6, 7, 9, 5])