In [1]:
import numpy as np

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [3]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [4]:
np.linspace(2.0, 3.0, 5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [5]:
np.linspace(2.0, 2.5, 5)

array([2.   , 2.125, 2.25 , 2.375, 2.5  ])

In [6]:
#Encontrando elementos únicos de um array

In [8]:
a = np.array([[1,2], [2,3], [3,3], [4,4]])
a

array([[1, 2],
       [2, 3],
       [3, 3],
       [4, 4]])

In [9]:
np.unique(a)

array([1, 2, 3, 4])